### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by chashmeetsingh** [chashmeetsingh/Online-Quiz-Application#1]
Code is messed up and lacks documentation, also to remove log messages

**Comment by sravi4701** [comment]
Please provide the description.

**Comment by chashmeetsingh** [comment]
@sravi4701 done

**Comment by elopezanaya** [comment]
are we talking about a refactor,pattern implementation, code best practices? or just a small clean up and improve the organization and documentation?

**Comment by chashmeetsingh** [comment]
@elopezanaya the latter

**Comment by elopezanaya** [comment]
hands on!
